name: Create/Update devcontainer


defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

permissions:
  packages: write


jobs:
  template-create-devcontainer:
    name: Create/Update the devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Variables 
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_ENV
          echo "DEVCONTAINER_PATH=${GITHUB_REPOSITORY@L}-devcontainer" >> $GITHUB_ENV

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{env.DEVCONTAINER_PATH}}
          cacheFrom: ghcr.io/${{env.DEVCONTAINER_PATH}}
          push: always
