name: Cpp devcontainer
run-name: ${{ github.event_name == 'workflow_dispatch' && ((github.event.inputs.image_tag == '' && github.sha || github.event.inputs.image_tag)(github.event.inputs.image_tag_isLatest && ', latest' || '' )) || ''}}
# 'Build container image with tag: '
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The tag version for the dev container image."
      image_tag_isLatest:
        description: "Tag the container image as latest."
        required: true
        type: boolean
        default: false
      devContainer_build_no_cache:
        description: "Disable the image cache from when building."
        required: true
        type: boolean
        default: false
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/cpp/**'
      - '.github/workflows/cicd-cpp.yml'

permissions:
  packages: write

env:
  devContainer_suffix: "-devcontainer"
  devContainer_name: "cpp"
  devContainer_folder: "src/cpp"
  devContainer_image_tag: ${{ github.event.inputs.image_tag == '' && github.sha || github.event.inputs.image_tag }}${{ github.event.inputs.image_tag_isLatest && ', latest' || '' }}

jobs:
  build-and-push:
    name: Create/Update the devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Lowercase Variables
      #   run: |
      #     echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_ENV
      #     echo "DEVCONTAINER_PATH=${GITHUB_REPOSITORY@L}-devcontainer" >> $GITHUB_ENV

      - name: Build container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{env.devContainer_folder}}
          noCache: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.devContainer_build_no_cache || false }}
          imageName: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          imageTag: ${{env.devContainer_image_tag}}
          push: always
