name: Hugo devcontainer
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Build container with tag ({0}{1})', (inputs.image_tag == '' && github.sha || inputs.image_tag), (inputs.image_tag_isLatest == true && ', latest' || '' )) || ''}}

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The tag version for the dev container image."
    image_tag_isLatest:
          description: "Tag the container image as latest."
          required: true
          type: boolean
          default: false
      devContainer_build_no_cache:
        description: "Disable the image cache from when building"
        required: true
        default: false
        type: boolean
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/hugo/**'
      - '.github/workflows/cicd-hugo.yml'

permissions:
  packages: write

env:
  devContainer_suffix: "-devcontainer"
  devContainer_name: "hugo"
  devContainer_folder: "src/hugo"
  devContainer_image_tag: ${{ inputs.image_tag == '' && github.sha || inputs.image_tag }}${{ inputs.image_tag_isLatest && ', latest' || '' }}

jobs:
  build-and-push:
    name: Create/Update the devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Lowercase Variables
      #   run: |
      #     echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_ENV
      #     echo "DEVCONTAINER_PATH=${GITHUB_REPOSITORY@L}-devcontainer" >> $GITHUB_ENV

      - name: Build container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{env.devContainer_folder}}
          noCache: ${{ github.event_name == 'workflow_dispatch' && inputs.devContainer_build_no_cache || false }}
          imageName: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          imageTag: ${{env.devContainer_image_tag}}
          push: always
