name: Cpp devcontainer


defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "The tag version for the dev container image."
  push:
    branches:
      - dev
      - main
    paths:
      - 'src/cpp/**'
      - '.github/workflows/cicd-cpp.yml'

permissions:
  packages: write

env:
  devContainer_suffix: "-devcontainer"
  devContainer_name: "cpp"
  devContainer_folder: "src/cpp"

jobs:
  build-and-push:
    name: Create/Update the devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Lowercase Variables 
      #   run: |
      #     echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_ENV
      #     echo "DEVCONTAINER_PATH=${GITHUB_REPOSITORY@L}-devcontainer" >> $GITHUB_ENV

      - name: Build container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{env.devContainer_folder}}
          imageName: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          imageTag: ${{github.run_id}}
          push: always

      - name: Build container image with image tag
        if: github.event.inputs.image_tag != ''
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{env.devContainer_folder}}
          imageName: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{env.devContainer_name}}${{env.devContainer_suffix}}
          imageTag: ${{github.event.inputs.image_tag}}
          push: always
